// Auto-generated by tokens/build.ts. Do not edit by hand.
// Run `npm run build:tokens` to regenerate.

export const sys = {
  "color": {
    "primary": "#075cba",
    "onPrimary": "#ffffff",
    "primaryContainer": "#070f36",
    "onPrimaryContainer": "#ffffff",
    "onPrimaryContainerVariant": "#b9dcff",
    "secondary": "#ffffff",
    "onSecondary": "#0f0f0f",
    "secondaryContainer": "#e6e6e6",
    "onSecondaryContainer": "#333333",
    "tertiary": "#ffffff",
    "onTertiary": "#0f0f0f",
    "tertiaryContainer": "#e6e6e6",
    "onTertiaryContainer": "#0f0f0f",
    "error": "#d82727",
    "onError": "#ffffff",
    "errorContainer": "#f7d4d4",
    "onErrorContainer": "#570f0f",
    "success": "#278647",
    "onSuccess": "#ffffff",
    "successContainer": "#c4e9d0",
    "onSuccessContainer": "#030c09",
    "warning": "#d67d00",
    "onWarning": "#ffffff",
    "warningContainer": "#fdeed9",
    "onWarningContainer": "#3a2304",
    "info": "#226cee",
    "onInfo": "#ffffff",
    "infoContainer": "#daecff",
    "onInfoContainer": "#162755",
    "surface": "#f3f4f6",
    "onSurface": "#1b1d22",
    "onSurfaceVariant": "#565f6c",
    "surfaceContainer": "#f3f4f6",
    "surfaceContainerLowest": "#ffffff",
    "surfaceContainerLow": "#f9fafb",
    "surfaceContainerHigh": "#eceeef",
    "surfaceContainerHighest": "#e6e8ea",
    "surfaceDim": "#eceeef",
    "surfaceBright": "#ffffff",
    "outline": "#ebecf0",
    "outlineVariant": "#d7dbe0",
    "outlineFixed": "#8a96a6",
    "outlineInverse": "#ffffff66",
    "inverseSurface": "#565f6c",
    "inverseOnSurface": "#ffffff",
    "inversePrimary": "#b9dcff",
    "primaryFixed": "#82b1ff",
    "primaryFixedDim": "#e3f2fd",
    "onPrimaryFixed": "#075cba",
    "onPrimaryFixedVariant": "#4285f4",
    "secondaryFixed": "#cccccc",
    "secondaryFixedDim": "#e6e6e6",
    "onSecondaryFixed": "#1a1a1a",
    "onSecondaryFixedVariant": "#666666",
    "transparent": {
      "primary08": "#075cba14",
      "white10": "#ffffff1a",
      "white20": "#ffffff33",
      "white30": "#ffffff4d",
      "white40": "#ffffff66",
      "white50": "#ffffff80",
      "white80": "#ffffffcc",
      "black10": "#0000001a",
      "black20": "#00000033",
      "black30": "#0000004d",
      "black40": "#00000066",
      "black50": "#00000080",
      "black80": "#000000cc"
    },
    "chart": {
      "1": "#b9dcff",
      "2": "#82b1ff",
      "3": "#4285f4",
      "4": "#075cba",
      "5": "#062e6f",
      "6": "#061545",
      "7": "#070f36",
      "8": "#050a24",
      "inactive": "#eceeef"
    }
  },
  "typography": {
    "displayLarge": {
      "fontFamily": "google sans",
      "fontSize": 80,
      "lineHeight": 80,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": -2.4
    },
    "displayMedium": {
      "fontFamily": "google sans",
      "fontSize": 72,
      "lineHeight": 79.2,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": -1.44
    },
    "displaySmall": {
      "fontFamily": "google sans",
      "fontSize": 64,
      "lineHeight": 76.8,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": -0.64
    },
    "headlineLarge": {
      "fontFamily": "google sans",
      "fontSize": 48,
      "lineHeight": 57.6,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": -0.48
    },
    "headlineMedium": {
      "fontFamily": "google sans",
      "fontSize": 40,
      "lineHeight": 48,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "headlineSmall": {
      "fontFamily": "google sans",
      "fontSize": 32,
      "lineHeight": 38.4,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "titleLarge": {
      "fontFamily": "google sans",
      "fontSize": 28,
      "lineHeight": 36.4,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "titleMedium": {
      "fontFamily": "google sans",
      "fontSize": 24,
      "lineHeight": 31.2,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "titleSmall": {
      "fontFamily": "google sans",
      "fontSize": 20,
      "lineHeight": 28,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "bodyLarge": {
      "fontFamily": "google sans",
      "fontSize": 20,
      "lineHeight": 30,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "bodyMedium": {
      "fontFamily": "google sans",
      "fontSize": 16,
      "lineHeight": 24,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "bodySmall": {
      "fontFamily": "google sans",
      "fontSize": 14,
      "lineHeight": 20,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "labelLarge": {
      "fontFamily": "google sans",
      "fontSize": 16,
      "lineHeight": 22.4,
      "fontWeight": "regular",
      "fontWeightEmphasized": "medium",
      "tracking": 0
    },
    "labelMedium": {
      "fontFamily": "google sans",
      "fontSize": 14,
      "lineHeight": 20,
      "fontWeight": "medium",
      "fontWeightEmphasized": "semibold",
      "tracking": 0.07
    },
    "labelSmall": {
      "fontFamily": "google sans",
      "fontSize": 12,
      "lineHeight": 18,
      "fontWeight": "medium",
      "fontWeightEmphasized": "semibold",
      "tracking": 0.12
    }
  },
  "spacing": {
    "none": 0,
    "3xs": 4,
    "2xs": 8,
    "xs": 12,
    "sm": 16,
    "md": 20,
    "lg": 24,
    "xl": 32,
    "2xl": 40,
    "3xl": 48,
    "4xl": 64,
    "5xl": 80
  },
  "radius": {
    "none": 0,
    "input": 4,
    "button": 8,
    "card": 12,
    "modal": 16,
    "banner": 24,
    "pill": 999
  },
  "borderWidth": {
    "none": 0,
    "default": 1,
    "emphasis": 2
  },
  "iconSize": {
    "xxs": 12,
    "xs": 16,
    "sm": 20,
    "md": 24,
    "lg": 32,
    "xl": 48
  },
  "state": {
    "hover": 8,
    "focused": 12,
    "pressed": 10,
    "disabledContainer": 48,
    "disabledContent": 64,
    "scrim": 10
  },
  "elevation": {
    "flat": {
      "shadow": {
        "color": "#00000000",
        "type": "dropShadow",
        "x": 0,
        "y": 0,
        "blur": 0,
        "spread": 0
      },
      "surfaceTintOpacity": 0
    },
    "resting": {
      "shadow": {
        "1": {
          "color": "#0000000f",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 4,
          "spread": 0
        },
        "2": {
          "color": "#0000000a",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 8,
          "spread": 0
        }
      },
      "surfaceTintOpacity": 0.05
    },
    "interactive": {
      "shadow": {
        "1": {
          "color": "#00000014",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 4,
          "spread": 0
        },
        "2": {
          "color": "#0000001a",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 16,
          "spread": 0
        }
      },
      "surfaceTintOpacity": 0.08
    },
    "floating": {
      "shadow": {
        "1": {
          "color": "#0000001f",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 6,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 16,
          "spread": 0
        }
      },
      "surfaceTintOpacity": 0.11
    },
    "overlay": {
      "shadow": {
        "1": {
          "color": "#0000001a",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 8,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 6,
          "blur": 20,
          "spread": 0
        }
      },
      "surfaceTintOpacity": 0.12
    },
    "modal": {
      "shadow": {
        "1": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 5,
          "blur": 8,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 8,
          "blur": 20,
          "spread": 0
        }
      },
      "surfaceTintOpacity": 0.14
    }
  }
} as const;

export type Sys = typeof sys;
